name: Terraform CI/CD

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    terraform:
        name: Terraform Workflow
        runs-on: ubuntu-latest

    steps:
        # Step 1: Checkout Code
        name: Checkout Code
        uses: actions/checkout@v3

        # Step 2: Setup Terraform
        name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
            terraform_version: 1.10.5       
        # Step 3: Initialize Terraform
        name: Terraform Init
        run: terraform init
        # Step 4: Validate Terraform Configuration
        name: Terraform Validate
        run: terraform validate
        # Step 5: Check Formatting
        name: Terraform Format
        run: terraform fmt -check
        # Step 6: Plan Terraform Changes
        name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan
        # Step 7: Apply Changes (Optional for Non-Production)
        name: Terraform Apply
        if: github.event_name == 'push'
        run: terraform apply -auto-approve tfplan
        
        